from typing import Any, Callable, Iterable, Protocol, TypeVar

class ClickException(Exception): ...

class Choice:
    def __init__(self, choices: Iterable[str], case_sensitive: bool = True) -> None: ...

F = TypeVar("F", bound=Callable[..., Any])

class _Command(Protocol):
    def __call__(self, func: F) -> F: ...

class _Group(_Command, Protocol):
    def command(self, *args: Any, **kwargs: Any) -> _Command: ...

class _CoreNamespace(Protocol):
    F: type[Any]

core: _CoreNamespace

def option(*args: Any, **kwargs: Any) -> _Command: ...
def group(*args: Any, **kwargs: Any) -> _Group: ...
def version_option(*args: Any, **kwargs: Any) -> _Command: ...
def echo(message: str) -> None: ...
