from typing import Any, Awaitable

class MessageBus:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def connect(self, handler: Any = ...) -> Awaitable["MessageBus"]: ...
    def request_name(self, name: str) -> Awaitable[int]: ...
    def export(self, path: str, iface: Any) -> None: ...
