from typing import Any, Callable

class ServiceInterface:
    def __init__(self, name: str) -> None: ...
    def emit_properties_changed(self, changed_properties: dict[str, Any]) -> None: ...

def method(*args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def signal(*args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
